#[maven]
#35.202.159.177
#[tomcat]
#34.65.240.26
---
- name: Install build software
  hosts: maven
  become: yes
  tasks:
 #   - name: Ensure git package is present
  #    apt:
  #      name: git
  #      state: present
   #     update_cache: yes
    - name: Ensure maven package is present
      apt:
        name: maven
        state: present
        update_cache: yes
    - name: Get git repo
     # shell: git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      git: repo=https://github.com/boxfuse/boxfuse-sample-java-war-hello.git dest=/home/ accept_hostkey=yes
    - name: Build maven clean package
      command: mvn -f /home/boxfuse-sample-java-war-hello/pom.xml clean package

- name: Install tomcat
  hosts: tomcat
  become: yes
  tasks:
    - name: Install basic java software
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - java-1.8.0-openjdk
        - tomcat8
    - name: Ensure tomcat service stop
      service:
        name: tomcat8
        state: stopped
    - name: Transfer file from maven to tomcat
      synchronize:
        src: home/boxfuse-sample-java-war-hello/target/hello-1.0.war
        dest: var/lib/tomcat8/webapps
        mode: pull
      delegate_to: tomcat
    - name: Ensure tomcat8 service is started
      service:
        name: tomcat8
        state: started
#    - name: Open port
#      rules:
#        proto: tcp
#          from_port: 8080
#          to_port: 8080
#          cidr_ip: 0.0.0.0/0