---
- name: Install build software
  hosts: maven
  become: yes
  tasks:
    - name: Ensure maven package is present
      apt:
        name: maven
        state: present
        update_cache: yes
    - name: Get git repo
      git: repo=https://github.com/boxfuse/boxfuse-sample-java-war-hello.git dest=/work/ accept_hostkey=yes
    - name: Build maven clean package
      command: mvn -f /work/pom.xml clean package
    - name: Pull war file
      fetch:
        src: /work/target/hello-1.0.war
        dest: /home
        flat: yes

- name: Install tomcat
  hosts: tomcat
  become: yes
  tasks:
    - name: Install basic java software
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - default-jdk
        - tomcat8
    - name: Ensure tomcat service stop
      service:
        name: tomcat8
        state: stopped
   # - name: Transfer file from maven to tomcat
   #   synchronize:
   #     src=/work/target/hello-1.0.war dest=/var/lib/tomcat8/hello-1.0.war
   #   delegate_to: tomcat
    - name: Push war file
      copy:
        src: /home/hello-1.0.war
        dest: /var/lib/tomcat8
    - name: Ensure tomcat8 service is started
      service:
        name: tomcat8
        state: started